server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现的方式找到其他微服务
          enabled: true
    sentinel:
      transport:
        dashboard: localhost:8080
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        # 开放暴露点
        include: "*"
  endpoint:
    health:
      show-details: always