server:
  port: 8091
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
logging:
  level:
    com.dute7liang.consumer.api.ProviderDemoClient: debug
management:
  endpoints:
    web:
      exposure:
        # 开放挂载点
        include: "*"
# nacos-provider 服务使用指定的负载均衡 ribbon
#nacos-provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# 表示ribbon是否启用饥饿加载。 默认不开启，则第一次访问会相对比较慢
#ribbon:
#  eager-load:
#    enabled: true
#    clients: ssss,ssss
feign:
  client:
    config:
      default: # 默认配置
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
#    config:
#      nacos-provider: # 单独的配置
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: full
#        errorDecoder: com.example.SimpleErrorDecoder
#        retryer: com.example.SimpleRetryer
#        requestInterceptors:
#          - com.example.FooRequestInterceptor
#          - com.example.BarRequestInterceptor
#        decode404: false
#        encoder: com.example.SimpleEncoder
#        decoder: com.example.SimpleDecoder
#        contract: com.example.SimpleContract