server:
  port: 8091
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
logging:
  level:
    com.dute7liang.consumer.api.ProviderDemoClient: debug
management:
  endpoints:
    web:
      exposure:
        # 开放暴露点
        include: "*"
feign:
  client:
    config:
      default: # 默认配置
        loggerLevel: basic
  sentinel:
    enabled: true